### ISSUE TITLE
D1 | New providers can register themselves on the system

### ISSUE THREAD

**Issue by maxvisser** [teamforus/testing#1]
@jamalv commented on [Wed Sep 16 2020](https://github.com/teamforus/implementation/issues/530)

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R8](https://forus.testquality.com/project/11150/testcase/255828/requirement/10816). Do not remove or edit.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R9](https://forus.testquality.com/project/11150/testcase/255829/requirement/10817). Do not remove or edit.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R10](https://forus.testquality.com/project/11150/testcase/255829/requirement/10818). Do not remove or edit.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R12](https://forus.testquality.com/project/11150/testcase/255828/requirement/10820). Do not remove or edit.
