### ISSUE TITLE
TestQuality | Add PVE as test suites

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/testing#13]
# TestQuality | Add PVE as test suites

For every project we win we receive requirements that we must meet. From the moment these requirements are known or we are a certain as a new project we should add them to TestQuality ASAP. This way we have we wil have a clear overview of what the status of meeting to requirements is and can have open communication about the results of these requirements.

## Upcoming projects
- [ ] Heumen
- [ ] Waalwijk
- [ ] Alkmaar (not certain yet)

**Comment by MichaelForus** [comment]
@GerbenBosschieter zijn hier al eisen voor bekend die ik kan verwerken in TQ?
