### ISSUE TITLE
D1 | At least the following information is required: Organization code, name, telephone number, e-mail, website, Chamber of Commerce number, IBAN number, Logo.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/testing#3]

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R11](https://forus.testquality.com/project/11150/testcase/255829/requirement/10819). Do not remove or edit.

**Comment by admin-forus** [comment]
https://forus.testquality.com requirement [R13](https://forus.testquality.com/project/11150/testcase/255828/requirement/10821). Do not remove or edit.
