### ISSUE TITLE
Sign-up as provider: Create profile in Me-app and test transaction - Fail

### ISSUE THREAD

**Issue by jamalv** [teamforus/testing#5]
**Step 1 Pass**

Fill 06 number

**Step 2 Pass**

Create profile in Me-app

**Step 3 Pass**

Click on link in e-mail

**Step 4 Fail**

Scan QR-code

**Step 5 Fail**

Create organization

**Step 6 Fail**

Create office

**Step 7 Fail**

Add employees

**Step 8 Fail**

Apply for fund

**Step 9 Fail**

Test transaction

this is a simple test

**Comment by jamalv** [comment]
https://forus.testquality.com defect [D5](https://forus.testquality.com/project/11150/result/2115503/defect/7209). Do not remove or edit.

**Comment by maxvisser** [comment]
Closed this issue as it was a test
